#!/bin/sh

CATALINA_HOME=/usr/local/tomcat8
PIDFILE=/var/run/tomcat8.pid
RETURN_VALUE=0
RUNAS_USER=tomcat

. /lib/lsb/init-functions

success() {
	log_end_msg 0
}

failure() {
	log_end_msg 1
}

start() {
	PID=`pgrep -f ${CATALINA_HOME}`
	if [ -s "${PIDFILE}" -a "${PID}" != "" ]; then
		log_begin_msg "Starting tomcat: "
		failure
		echo
		return 1
	fi

	su - ${RUNAS_USER} -c "${CATALINA_HOME}/bin/startup.sh"
	log_begin_msg "Starting tomcat: "
	PID=`pgrep -f ${CATALINA_HOME}`
	if [ "${PID}" != "" ]; then
		success
		echo ${PID} > ${PIDFILE}
		echo
		return 0
	else
		failure
		echo
		return 1
	fi
}

stop() {
	PID=`pgrep -f ${CATALINA_HOME}`
	if [ "${PID}" != "" ]; then
		su - ${RUNAS_USER} -c "${CATALINA_HOME}/bin/shutdown.sh"
		log_begin_msg "Stopping tomcat: "
		rm -f ${PIDFILE} && success || failure
		RETURN_VALUE=$?
		echo
		return ${RETURN_VALUE}
	else
		log_begin_msg "Stopping tomcat: "
		failure
		echo
		return 1
	fi
}

restart() {
	stop
	sleep 5
	if [ $? -eq 0 ]; then
		start
	fi
}

status() {
	PID=`pgrep -f ${CATALINA_HOME}`
	if [ "${PID}" != "" ]; then
		log_begin_msg "tomcat is running (pid ${PID})"
	else
		log_begin_msg "tomcat is not running"
	fi
	return 0
}

usage() {
	echo "Usage: ${0} {start|stop|restart}"
	return 1
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		usage
		;;
esac

exit $?
